export const env = `# MAIL
MAIL_HOST=MAIL_HOST
MAIL_SERVICE=MAIL_SERVICE
MAIL_PORT=MAIL_PORT
MAIL_USER=MAIL_USER
MAIL_PASS=MAIL_PASS
MAIL_CIPHERS=MAIL_CIPHERS
# END MAIL

# SERVER
APP_PORT=4003
APP_HOSTNAME=http://localhost
APP_NAME=APP_NAME
TOKEN_EXPIRE_TIME=4h
TOKEN_EXPIRE_TIME_REFRESH=30d
TOKEN_SECRET=TOKEN_SECRET
TOKEN_TYPE=TOKEN_TYPE
ENCRYPTION_KEY=ENCRYPTION_KEY
NODE_ENV=DEV
# END SERVER

# SWAGGER
SWAGGER_USERNAME=SWAGGER_USERNAME
SWAGGER_PASSWORD=SWAGGER_PASSWORD
# END SWAGGER

# DATABASE
DATABASE_TYPE=mysql
DATABASE_HOSTNAME=project_db
DATABASE_PORT=3306
DATABASE_USER=root
DATABASE_PASSWORD=root
DATABASE_NAME=project_db
DATABASE_SYNC=false
# END DATABASE`;
